### ISSUE TITLE
Add CMake support

### ISSUE THREAD

**Issue by Ranzeplay** [0382/util#1]
I really love your work and I want to use it in my project. Could you add CMake support for it so that everyone can use it in their CMake projects?

**Comment by 0382** [comment]
Well, as the description, this is just a collection of some code snippets. I think only the `argparse` , `inifile` and `range` are useful, and all of them are head-only packages. Just copy the head file to your include directory, and `#include` it in your code. Other codes are not well designed, and I don't want to improve them recently. So I think CMake is not needed currently.

**Comment by Ranzeplay** [comment]
Well, okay. I'll use it in my code under license
